# coding: utf-8

"""
    DraCor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.2
    Contact: fr.fischer@fu-berlin.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.external_reference_resource_id import ExternalReferenceResourceId
from typing import Optional, Set
from typing_extensions import Self

class AuthorInPlayInCorpus(BaseModel):
    """
    AuthorInPlayInCorpus
    """ # noqa: E501
    refs: Optional[List[ExternalReferenceResourceId]] = None
    also_known_as: Optional[List[StrictStr]] = Field(default=None, alias="alsoKnownAs")
    fullname_en: Optional[StrictStr] = Field(default=None, alias="fullnameEn")
    name: Optional[StrictStr] = None
    shortname_en: Optional[StrictStr] = Field(default=None, alias="shortnameEn")
    name_en: Optional[StrictStr] = Field(default=None, alias="nameEn")
    fullname: Optional[StrictStr] = None
    shortname: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["refs", "alsoKnownAs", "fullnameEn", "name", "shortnameEn", "nameEn", "fullname", "shortname"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AuthorInPlayInCorpus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in refs (list)
        _items = []
        if self.refs:
            for _item in self.refs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['refs'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AuthorInPlayInCorpus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "refs": [ExternalReferenceResourceId.from_dict(_item) for _item in obj["refs"]] if obj.get("refs") is not None else None,
            "alsoKnownAs": obj.get("alsoKnownAs"),
            "fullnameEn": obj.get("fullnameEn"),
            "name": obj.get("name"),
            "shortnameEn": obj.get("shortnameEn"),
            "nameEn": obj.get("nameEn"),
            "fullname": obj.get("fullname"),
            "shortname": obj.get("shortname")
        })
        return _obj


