# coding: utf-8

"""
    DraCor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.2
    Contact: fr.fischer@fu-berlin.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class Character(BaseModel):
    """
    Character
    """ # noqa: E501
    closeness: Optional[Union[StrictFloat, StrictInt]] = None
    wikidata_id: Optional[StrictStr] = Field(default=None, alias="wikidataId")
    betweenness: Optional[Union[StrictFloat, StrictInt]] = None
    degree: Optional[StrictInt] = None
    weighted_degree: Optional[StrictInt] = Field(default=None, alias="weightedDegree")
    num_of_speech_acts: Optional[StrictInt] = Field(default=None, alias="numOfSpeechActs")
    id: Optional[StrictStr] = None
    eigenvector: Optional[Union[StrictFloat, StrictInt]] = None
    num_of_scenes: Optional[StrictInt] = Field(default=None, alias="numOfScenes")
    num_of_words: Optional[StrictInt] = Field(default=None, alias="numOfWords")
    is_group: Optional[StrictBool] = Field(default=None, alias="isGroup")
    name: Optional[StrictStr] = None
    gender: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["closeness", "wikidataId", "betweenness", "degree", "weightedDegree", "numOfSpeechActs", "id", "eigenvector", "numOfScenes", "numOfWords", "isGroup", "name", "gender"]

    @field_validator('gender')
    def gender_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['MALE', 'FEMALE', 'UNKNOWN']):
            raise ValueError("must be one of enum values ('MALE', 'FEMALE', 'UNKNOWN')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Character from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if closeness (nullable) is None
        # and model_fields_set contains the field
        if self.closeness is None and "closeness" in self.model_fields_set:
            _dict['closeness'] = None

        # set to None if betweenness (nullable) is None
        # and model_fields_set contains the field
        if self.betweenness is None and "betweenness" in self.model_fields_set:
            _dict['betweenness'] = None

        # set to None if degree (nullable) is None
        # and model_fields_set contains the field
        if self.degree is None and "degree" in self.model_fields_set:
            _dict['degree'] = None

        # set to None if weighted_degree (nullable) is None
        # and model_fields_set contains the field
        if self.weighted_degree is None and "weighted_degree" in self.model_fields_set:
            _dict['weightedDegree'] = None

        # set to None if eigenvector (nullable) is None
        # and model_fields_set contains the field
        if self.eigenvector is None and "eigenvector" in self.model_fields_set:
            _dict['eigenvector'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if gender (nullable) is None
        # and model_fields_set contains the field
        if self.gender is None and "gender" in self.model_fields_set:
            _dict['gender'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Character from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "closeness": obj.get("closeness"),
            "wikidataId": obj.get("wikidataId"),
            "betweenness": obj.get("betweenness"),
            "degree": obj.get("degree"),
            "weightedDegree": obj.get("weightedDegree"),
            "numOfSpeechActs": obj.get("numOfSpeechActs"),
            "id": obj.get("id"),
            "eigenvector": obj.get("eigenvector"),
            "numOfScenes": obj.get("numOfScenes"),
            "numOfWords": obj.get("numOfWords"),
            "isGroup": obj.get("isGroup"),
            "name": obj.get("name"),
            "gender": obj.get("gender")
        })
        return _obj


