# coding: utf-8

"""
    DraCor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.2
    Contact: fr.fischer@fu-berlin.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.corpus_metrics import CorpusMetrics
from typing import Optional, Set
from typing_extensions import Self

class CorpusInCorpora(BaseModel):
    """
    CorpusInCorpora
    """ # noqa: E501
    acronym: Optional[StrictStr] = None
    metrics: Optional[CorpusMetrics] = None
    title: Optional[StrictStr] = None
    licence: Optional[StrictStr] = None
    licence_url: Optional[StrictStr] = Field(default=None, alias="licenceUrl")
    uri: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    repository: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["acronym", "metrics", "title", "licence", "licenceUrl", "uri", "description", "name", "repository"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CorpusInCorpora from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metrics
        if self.metrics:
            _dict['metrics'] = self.metrics.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CorpusInCorpora from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "acronym": obj.get("acronym"),
            "metrics": CorpusMetrics.from_dict(obj["metrics"]) if obj.get("metrics") is not None else None,
            "title": obj.get("title"),
            "licence": obj.get("licence"),
            "licenceUrl": obj.get("licenceUrl"),
            "uri": obj.get("uri"),
            "description": obj.get("description"),
            "name": obj.get("name"),
            "repository": obj.get("repository")
        })
        return _obj


