# coding: utf-8

"""
    DraCor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.2
    Contact: fr.fischer@fu-berlin.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from openapi_client.models.author_in_play_metadata import AuthorInPlayMetadata
from openapi_client.models.character_in_play_metadata import CharacterInPlayMetadata
from openapi_client.models.relation_item_in_play_metadata import RelationItemInPlayMetadata
from openapi_client.models.segment_item_in_play_metadata import SegmentItemInPlayMetadata
from openapi_client.models.source_in_play_metadata import SourceInPlayMetadata
from typing import Optional, Set
from typing_extensions import Self

class Play(BaseModel):
    """
    Play
    """ # noqa: E501
    wikidata_id: Optional[StrictStr] = Field(default=None, alias="wikidataId")
    segments: Optional[List[SegmentItemInPlayMetadata]] = None
    corpus: Optional[StrictStr] = None
    year_premiered: Optional[StrictStr] = Field(default=None, alias="yearPremiered")
    all_in_index: Optional[Union[Annotated[float, Field(le=1.0, strict=True, ge=0.0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = Field(default=None, alias="allInIndex")
    title_en: Optional[StrictStr] = Field(default=None, alias="titleEn")
    authors: Optional[List[AuthorInPlayMetadata]] = None
    name: Optional[StrictStr] = None
    normalized_genre: Optional[StrictStr] = Field(default=None, alias="normalizedGenre")
    subtitle_en: Optional[StrictStr] = Field(default=None, alias="subtitleEn")
    characters: Optional[List[CharacterInPlayMetadata]] = None
    source: Optional[SourceInPlayMetadata] = None
    subtitle: Optional[StrictStr] = None
    libretto: Optional[StrictBool] = None
    all_in_segment: Optional[StrictInt] = Field(default=None, alias="allInSegment")
    year_written: Optional[StrictStr] = Field(default=None, alias="yearWritten")
    id: Optional[StrictStr] = None
    date_premiered: Optional[StrictStr] = Field(default=None, alias="datePremiered")
    year_printed: Optional[StrictStr] = Field(default=None, alias="yearPrinted")
    relations: Optional[List[RelationItemInPlayMetadata]] = None
    title: Optional[StrictStr] = None
    year_normalized: Optional[StrictInt] = Field(default=None, alias="yearNormalized")
    original_source: Optional[StrictStr] = Field(default=None, alias="originalSource")
    __properties: ClassVar[List[str]] = ["wikidataId", "segments", "corpus", "yearPremiered", "allInIndex", "titleEn", "authors", "name", "normalizedGenre", "subtitleEn", "characters", "source", "subtitle", "libretto", "allInSegment", "yearWritten", "id", "datePremiered", "yearPrinted", "relations", "title", "yearNormalized", "originalSource"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Play from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in segments (list)
        _items = []
        if self.segments:
            for _item in self.segments:
                if _item:
                    _items.append(_item.to_dict())
            _dict['segments'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in authors (list)
        _items = []
        if self.authors:
            for _item in self.authors:
                if _item:
                    _items.append(_item.to_dict())
            _dict['authors'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in characters (list)
        _items = []
        if self.characters:
            for _item in self.characters:
                if _item:
                    _items.append(_item.to_dict())
            _dict['characters'] = _items
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in relations (list)
        _items = []
        if self.relations:
            for _item in self.relations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['relations'] = _items
        # set to None if wikidata_id (nullable) is None
        # and model_fields_set contains the field
        if self.wikidata_id is None and "wikidata_id" in self.model_fields_set:
            _dict['wikidataId'] = None

        # set to None if year_premiered (nullable) is None
        # and model_fields_set contains the field
        if self.year_premiered is None and "year_premiered" in self.model_fields_set:
            _dict['yearPremiered'] = None

        # set to None if all_in_index (nullable) is None
        # and model_fields_set contains the field
        if self.all_in_index is None and "all_in_index" in self.model_fields_set:
            _dict['allInIndex'] = None

        # set to None if normalized_genre (nullable) is None
        # and model_fields_set contains the field
        if self.normalized_genre is None and "normalized_genre" in self.model_fields_set:
            _dict['normalizedGenre'] = None

        # set to None if subtitle (nullable) is None
        # and model_fields_set contains the field
        if self.subtitle is None and "subtitle" in self.model_fields_set:
            _dict['subtitle'] = None

        # set to None if all_in_segment (nullable) is None
        # and model_fields_set contains the field
        if self.all_in_segment is None and "all_in_segment" in self.model_fields_set:
            _dict['allInSegment'] = None

        # set to None if year_written (nullable) is None
        # and model_fields_set contains the field
        if self.year_written is None and "year_written" in self.model_fields_set:
            _dict['yearWritten'] = None

        # set to None if year_printed (nullable) is None
        # and model_fields_set contains the field
        if self.year_printed is None and "year_printed" in self.model_fields_set:
            _dict['yearPrinted'] = None

        # set to None if year_normalized (nullable) is None
        # and model_fields_set contains the field
        if self.year_normalized is None and "year_normalized" in self.model_fields_set:
            _dict['yearNormalized'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Play from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "wikidataId": obj.get("wikidataId"),
            "segments": [SegmentItemInPlayMetadata.from_dict(_item) for _item in obj["segments"]] if obj.get("segments") is not None else None,
            "corpus": obj.get("corpus"),
            "yearPremiered": obj.get("yearPremiered"),
            "allInIndex": obj.get("allInIndex"),
            "titleEn": obj.get("titleEn"),
            "authors": [AuthorInPlayMetadata.from_dict(_item) for _item in obj["authors"]] if obj.get("authors") is not None else None,
            "name": obj.get("name"),
            "normalizedGenre": obj.get("normalizedGenre"),
            "subtitleEn": obj.get("subtitleEn"),
            "characters": [CharacterInPlayMetadata.from_dict(_item) for _item in obj["characters"]] if obj.get("characters") is not None else None,
            "source": SourceInPlayMetadata.from_dict(obj["source"]) if obj.get("source") is not None else None,
            "subtitle": obj.get("subtitle"),
            "libretto": obj.get("libretto"),
            "allInSegment": obj.get("allInSegment"),
            "yearWritten": obj.get("yearWritten"),
            "id": obj.get("id"),
            "datePremiered": obj.get("datePremiered"),
            "yearPrinted": obj.get("yearPrinted"),
            "relations": [RelationItemInPlayMetadata.from_dict(_item) for _item in obj["relations"]] if obj.get("relations") is not None else None,
            "title": obj.get("title"),
            "yearNormalized": obj.get("yearNormalized"),
            "originalSource": obj.get("originalSource")
        })
        return _obj


