# coding: utf-8

"""
    DraCor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.2
    Contact: fr.fischer@fu-berlin.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.node_in_play_metrics import NodeInPlayMetrics
from typing import Optional, Set
from typing_extensions import Self

class PlayMetrics(BaseModel):
    """
    PlayMetrics
    """ # noqa: E501
    average_path_length: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="averagePathLength")
    diameter: Optional[StrictInt] = None
    nodes: Optional[List[NodeInPlayMetrics]] = None
    corpus: Optional[StrictStr] = None
    average_clustering: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="averageClustering")
    max_degree: Optional[StrictInt] = Field(default=None, alias="maxDegree")
    wikipedia_link_count: Optional[StrictInt] = Field(default=None, alias="wikipediaLinkCount")
    id: Optional[StrictStr] = None
    num_edges: Optional[StrictInt] = Field(default=None, alias="numEdges")
    size: Optional[StrictInt] = None
    average_degree: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="averageDegree")
    name: Optional[StrictStr] = None
    max_degree_ids: Optional[List[StrictStr]] = Field(default=None, alias="maxDegreeIds")
    num_connected_components: Optional[StrictInt] = Field(default=None, alias="numConnectedComponents")
    density: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["averagePathLength", "diameter", "nodes", "corpus", "averageClustering", "maxDegree", "wikipediaLinkCount", "id", "numEdges", "size", "averageDegree", "name", "maxDegreeIds", "numConnectedComponents", "density"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlayMetrics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in nodes (list)
        _items = []
        if self.nodes:
            for _item in self.nodes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['nodes'] = _items
        # set to None if wikipedia_link_count (nullable) is None
        # and model_fields_set contains the field
        if self.wikipedia_link_count is None and "wikipedia_link_count" in self.model_fields_set:
            _dict['wikipediaLinkCount'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlayMetrics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "averagePathLength": obj.get("averagePathLength"),
            "diameter": obj.get("diameter"),
            "nodes": [NodeInPlayMetrics.from_dict(_item) for _item in obj["nodes"]] if obj.get("nodes") is not None else None,
            "corpus": obj.get("corpus"),
            "averageClustering": obj.get("averageClustering"),
            "maxDegree": obj.get("maxDegree"),
            "wikipediaLinkCount": obj.get("wikipediaLinkCount"),
            "id": obj.get("id"),
            "numEdges": obj.get("numEdges"),
            "size": obj.get("size"),
            "averageDegree": obj.get("averageDegree"),
            "name": obj.get("name"),
            "maxDegreeIds": obj.get("maxDegreeIds"),
            "numConnectedComponents": obj.get("numConnectedComponents"),
            "density": obj.get("density")
        })
        return _obj


