# coding: utf-8

"""
    DraCor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.2
    Contact: fr.fischer@fu-berlin.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr, field_validator
from typing import Any, Dict, Optional
from typing_extensions import Annotated

from openapi_client.api_client import ApiClient, RequestSerialized
from openapi_client.api_response import ApiResponse
from openapi_client.rest import RESTResponseType


class WebhookApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def github_webhook(
        self,
        user_agent: Annotated[str, Field(strict=True)],
        x_git_hub_delivery: StrictStr,
        x_git_hub_event: StrictStr,
        x_hub_signature: StrictStr,
        body: Annotated[Optional[Dict[str, Any]], Field(description="Webhook payload (see https://developer.github.com/webhooks/#payloads)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """GitHub Webhook

        Endpoint accepting POST requests from Github (see https://developer.github.com/webhooks/). We currently only handle push events on the main branch.

        :param user_agent: (required)
        :type user_agent: str
        :param x_git_hub_delivery: (required)
        :type x_git_hub_delivery: str
        :param x_git_hub_event: (required)
        :type x_git_hub_event: str
        :param x_hub_signature: (required)
        :type x_hub_signature: str
        :param body: Webhook payload (see https://developer.github.com/webhooks/#payloads)
        :type body: object
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._github_webhook_serialize(
            user_agent=user_agent,
            x_git_hub_delivery=x_git_hub_delivery,
            x_git_hub_event=x_git_hub_event,
            x_hub_signature=x_hub_signature,
            body=body,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def github_webhook_with_http_info(
        self,
        user_agent: Annotated[str, Field(strict=True)],
        x_git_hub_delivery: StrictStr,
        x_git_hub_event: StrictStr,
        x_hub_signature: StrictStr,
        body: Annotated[Optional[Dict[str, Any]], Field(description="Webhook payload (see https://developer.github.com/webhooks/#payloads)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """GitHub Webhook

        Endpoint accepting POST requests from Github (see https://developer.github.com/webhooks/). We currently only handle push events on the main branch.

        :param user_agent: (required)
        :type user_agent: str
        :param x_git_hub_delivery: (required)
        :type x_git_hub_delivery: str
        :param x_git_hub_event: (required)
        :type x_git_hub_event: str
        :param x_hub_signature: (required)
        :type x_hub_signature: str
        :param body: Webhook payload (see https://developer.github.com/webhooks/#payloads)
        :type body: object
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._github_webhook_serialize(
            user_agent=user_agent,
            x_git_hub_delivery=x_git_hub_delivery,
            x_git_hub_event=x_git_hub_event,
            x_hub_signature=x_hub_signature,
            body=body,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def github_webhook_without_preload_content(
        self,
        user_agent: Annotated[str, Field(strict=True)],
        x_git_hub_delivery: StrictStr,
        x_git_hub_event: StrictStr,
        x_hub_signature: StrictStr,
        body: Annotated[Optional[Dict[str, Any]], Field(description="Webhook payload (see https://developer.github.com/webhooks/#payloads)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """GitHub Webhook

        Endpoint accepting POST requests from Github (see https://developer.github.com/webhooks/). We currently only handle push events on the main branch.

        :param user_agent: (required)
        :type user_agent: str
        :param x_git_hub_delivery: (required)
        :type x_git_hub_delivery: str
        :param x_git_hub_event: (required)
        :type x_git_hub_event: str
        :param x_hub_signature: (required)
        :type x_hub_signature: str
        :param body: Webhook payload (see https://developer.github.com/webhooks/#payloads)
        :type body: object
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._github_webhook_serialize(
            user_agent=user_agent,
            x_git_hub_delivery=x_git_hub_delivery,
            x_git_hub_event=x_git_hub_event,
            x_hub_signature=x_hub_signature,
            body=body,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _github_webhook_serialize(
        self,
        user_agent,
        x_git_hub_delivery,
        x_git_hub_event,
        x_hub_signature,
        body,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if user_agent is not None:
            _header_params['User-Agent'] = user_agent
        if x_git_hub_delivery is not None:
            _header_params['X-GitHub-Delivery'] = x_git_hub_delivery
        if x_git_hub_event is not None:
            _header_params['X-GitHub-Event'] = x_git_hub_event
        if x_hub_signature is not None:
            _header_params['X-Hub-Signature'] = x_hub_signature
        # process the form parameters
        # process the body parameter
        if body is not None:
            _body_params = body


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/webhook/github',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


