name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1
  CLICOLOR_FORCE: 1

jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      dracor-api:
        image: docker:20.10.7
        options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Start the docker-compose stack
        run: docker compose -f test/compose.dracor_api.dev.yml up --detach --wait
      - name: Test if /info returns a response
        run: curl --verbose http://localhost:8088/exist/restxq/v1/info
      - name: Add test corpus
        run: |
          curl https://raw.githubusercontent.com/dracor-org/testdracor/main/corpus.xml | \
          curl -X POST \
          -u admin: \
          -d@- \
          -H 'Content-type: text/xml' \
          http://localhost:8088/api/v1/corpora
      - name: Load data for test corpus
        run: |
          curl -X POST \
          -u admin: \
          -H 'Content-type: application/json' \
          -d '{"load":true}' \
          http://localhost:8088/api/v1/corpora/test
      - name: Wait 30 seconds for corpus data loading to complete
        run: sleep 30
      - name: Test if corpus returns a response
        run: curl --verbose http://localhost:8088/api/v1/corpora/test
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install --upgrade pip
      - run: python -m pip install --editable .
      - run: python -m pip install pytest
      - run: pytest test/test_api_wrapper.py -v -ra --showlocals
