# coding: utf-8

"""
    DraCor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.2
    Contact: fr.fischer@fu-berlin.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.wikidata_api import WikidataApi


class TestWikidataApi(unittest.TestCase):
    """WikidataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WikidataApi()

    def tearDown(self) -> None:
        pass

    def test_wikidata_author_info(self) -> None:
        """Test case for wikidata_author_info

        List author information from Wikidata
        """
        pass

    def test_wikidata_mixnmatch(self) -> None:
        """Test case for wikidata_mixnmatch

        Endpoint for Wikidata Mix'n'match
        """
        pass


if __name__ == '__main__':
    unittest.main()
