# coding: utf-8

"""
    DraCor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.2
    Contact: fr.fischer@fu-berlin.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.character import Character

class TestCharacter(unittest.TestCase):
    """Character unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Character:
        """Test Character
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Character`
        """
        model = Character()
        if include_optional:
            return Character(
                closeness = 1.337,
                wikidata_id = '',
                betweenness = 1.337,
                degree = 56,
                weighted_degree = 56,
                num_of_speech_acts = 56,
                id = '',
                eigenvector = 1.337,
                num_of_scenes = 56,
                num_of_words = 56,
                is_group = True,
                name = '',
                gender = 'MALE'
            )
        else:
            return Character(
        )
        """

    def testCharacter(self):
        """Test Character"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
