# coding: utf-8

"""
    DraCor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.2
    Contact: fr.fischer@fu-berlin.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.play_with_wikidata_character import PlayWithWikidataCharacter

class TestPlayWithWikidataCharacter(unittest.TestCase):
    """PlayWithWikidataCharacter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlayWithWikidataCharacter:
        """Test PlayWithWikidataCharacter
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlayWithWikidataCharacter`
        """
        model = PlayWithWikidataCharacter()
        if include_optional:
            return PlayWithWikidataCharacter(
                character_name = '',
                title = '',
                id = '',
                uri = '',
                authors = [
                    ''
                    ]
            )
        else:
            return PlayWithWikidataCharacter(
        )
        """

    def testPlayWithWikidataCharacter(self):
        """Test PlayWithWikidataCharacter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
