# coding: utf-8

"""
    DraCor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.2
    Contact: fr.fischer@fu-berlin.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.segment_item_in_play_metadata import SegmentItemInPlayMetadata

class TestSegmentItemInPlayMetadata(unittest.TestCase):
    """SegmentItemInPlayMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SegmentItemInPlayMetadata:
        """Test SegmentItemInPlayMetadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SegmentItemInPlayMetadata`
        """
        model = SegmentItemInPlayMetadata()
        if include_optional:
            return SegmentItemInPlayMetadata(
                type = '',
                speakers = [
                    ''
                    ],
                number = 56,
                title = ''
            )
        else:
            return SegmentItemInPlayMetadata(
        )
        """

    def testSegmentItemInPlayMetadata(self):
        """Test SegmentItemInPlayMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
