# coding: utf-8

"""
    DraCor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.2
    Contact: fr.fischer@fu-berlin.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.play_metadata import PlayMetadata

class TestPlayMetadata(unittest.TestCase):
    """PlayMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlayMetadata:
        """Test PlayMetadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlayMetadata`
        """
        model = PlayMetadata()
        if include_optional:
            return PlayMetadata(
                num_of_speakers_male = 56,
                diameter = 56,
                wikidata_id = '',
                num_of_speakers_female = 56,
                average_clustering = 1.337,
                year_premiered = '',
                original_source_pub_place = '',
                num_of_speakers = 56,
                name = '',
                word_count_stage = 56,
                normalized_genre = '',
                num_of_l = 56,
                word_count_sp = 56,
                num_of_speakers_unknown = 56,
                average_path_length = 1.337,
                original_source_year = 56,
                max_degree = 56,
                num_edges = 56,
                subtitle = '',
                first_author = '',
                original_source_publisher = '',
                libretto = True,
                num_connected_components = 56,
                year_written = '',
                play_name = '',
                num_of_p = 56,
                id = '',
                word_count_text = 56,
                date_premiered = '',
                size = 56,
                average_degree = 1.337,
                year_printed = '',
                num_of_segments = 56,
                num_of_acts = 56,
                title = '',
                wikipedia_link_count = 56,
                digital_source = None,
                num_of_person_groups = 56,
                year_normalized = 56,
                num_of_co_authors = 56,
                max_degree_ids = '',
                original_source_number_of_pages = 56,
                density = 1.337
            )
        else:
            return PlayMetadata(
        )
        """

    def testPlayMetadata(self):
        """Test PlayMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
