# coding: utf-8

"""
    DraCor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.2
    Contact: fr.fischer@fu-berlin.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.load_corpus_request import LoadCorpusRequest

class TestLoadCorpusRequest(unittest.TestCase):
    """LoadCorpusRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoadCorpusRequest:
        """Test LoadCorpusRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LoadCorpusRequest`
        """
        model = LoadCorpusRequest()
        if include_optional:
            return LoadCorpusRequest(
                load = True
            )
        else:
            return LoadCorpusRequest(
                load = True,
        )
        """

    def testLoadCorpusRequest(self):
        """Test LoadCorpusRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
