# coding: utf-8

"""
    DraCor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.2
    Contact: fr.fischer@fu-berlin.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.corpus_metrics import CorpusMetrics

class TestCorpusMetrics(unittest.TestCase):
    """CorpusMetrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CorpusMetrics:
        """Test CorpusMetrics
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CorpusMetrics`
        """
        model = CorpusMetrics()
        if include_optional:
            return CorpusMetrics(
                characters = 56,
                stage = 56,
                updated = '',
                sp = 56,
                text = 56,
                plays = 56,
                wordcount = openapi_client.models.word_counts.WordCounts(
                    text = 56, 
                    stage = 56, 
                    sp = 56, ),
                male = 56,
                female = 56
            )
        else:
            return CorpusMetrics(
        )
        """

    def testCorpusMetrics(self):
        """Test CorpusMetrics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
