# coding: utf-8

"""
    DraCor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.2
    Contact: fr.fischer@fu-berlin.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.play_metrics import PlayMetrics

class TestPlayMetrics(unittest.TestCase):
    """PlayMetrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlayMetrics:
        """Test PlayMetrics
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlayMetrics`
        """
        model = PlayMetrics()
        if include_optional:
            return PlayMetrics(
                average_path_length = 1.337,
                diameter = 56,
                nodes = [
                    openapi_client.models.node_in_play_metrics.NodeInPlayMetrics(
                        closeness = 1.337, 
                        betweenness = 1.337, 
                        degree = 56, 
                        weighted_degree = 56, 
                        id = '', 
                        eigenvector = 1.337, )
                    ],
                corpus = '',
                average_clustering = 1.337,
                max_degree = 56,
                wikipedia_link_count = 56,
                id = '',
                num_edges = 56,
                size = 56,
                average_degree = 1.337,
                name = '',
                max_degree_ids = [
                    ''
                    ],
                num_connected_components = 56,
                density = 1.337
            )
        else:
            return PlayMetrics(
        )
        """

    def testPlayMetrics(self):
        """Test PlayMetrics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
