# coding: utf-8

"""
    DraCor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.2
    Contact: fr.fischer@fu-berlin.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.node_in_play_metrics import NodeInPlayMetrics

class TestNodeInPlayMetrics(unittest.TestCase):
    """NodeInPlayMetrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodeInPlayMetrics:
        """Test NodeInPlayMetrics
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodeInPlayMetrics`
        """
        model = NodeInPlayMetrics()
        if include_optional:
            return NodeInPlayMetrics(
                closeness = 1.337,
                betweenness = 1.337,
                degree = 56,
                weighted_degree = 56,
                id = '',
                eigenvector = 1.337
            )
        else:
            return NodeInPlayMetrics(
        )
        """

    def testNodeInPlayMetrics(self):
        """Test NodeInPlayMetrics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
