# coding: utf-8

"""
    DraCor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.2
    Contact: fr.fischer@fu-berlin.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_api import AdminApi


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminApi()

    def tearDown(self) -> None:
        pass

    def test_delete_corpus(self) -> None:
        """Test case for delete_corpus

        Remove corpus from database
        """
        pass

    def test_load_corpus(self) -> None:
        """Test case for load_corpus

        Load corpus data from its repository
        """
        pass

    def test_play_delete(self) -> None:
        """Test case for play_delete

        Remove a single play from the corpus
        """
        pass

    def test_play_tei_put(self) -> None:
        """Test case for play_tei_put

        Add new or update existing TEI document
        """
        pass

    def test_post_corpora(self) -> None:
        """Test case for post_corpora

        Add new corpus
        """
        pass


if __name__ == '__main__':
    unittest.main()
