# coding: utf-8

"""
    DraCor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.2
    Contact: fr.fischer@fu-berlin.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.play_in_corpus import PlayInCorpus

class TestPlayInCorpus(unittest.TestCase):
    """PlayInCorpus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlayInCorpus:
        """Test PlayInCorpus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlayInCorpus`
        """
        model = PlayInCorpus()
        if include_optional:
            return PlayInCorpus(
                wikidata_id = '',
                year_written = '',
                source = openapi_client.models.source_in_play_metadata.SourceInPlayMetadata(
                    url = null, 
                    name = '', ),
                year_premiered = '',
                title = '',
                networkdata_csv_url = '',
                id = '',
                title_en = '',
                subtitle = '',
                date_premiered = '',
                year_printed = '',
                year_normalized = 56,
                authors = [
                    openapi_client.models.author_in_play_in_corpus.AuthorInPlayInCorpus(
                        refs = [
                            openapi_client.models.external_reference_resource_id.ExternalReferenceResourceId(
                                type = '', 
                                ref = '', )
                            ], 
                        also_known_as = [
                            ''
                            ], 
                        fullname_en = '', 
                        name = '', 
                        shortname_en = '', 
                        name_en = '', 
                        fullname = '', 
                        shortname = '', )
                    ],
                name = '',
                network_size = 56,
                subtitle_en = ''
            )
        else:
            return PlayInCorpus(
        )
        """

    def testPlayInCorpus(self):
        """Test PlayInCorpus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
