# coding: utf-8

"""
    DraCor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.2
    Contact: fr.fischer@fu-berlin.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.author_in_play_metadata import AuthorInPlayMetadata

class TestAuthorInPlayMetadata(unittest.TestCase):
    """AuthorInPlayMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthorInPlayMetadata:
        """Test AuthorInPlayMetadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthorInPlayMetadata`
        """
        model = AuthorInPlayMetadata()
        if include_optional:
            return AuthorInPlayMetadata(
                refs = [
                    openapi_client.models.external_reference_resource_id.ExternalReferenceResourceId(
                        type = '', 
                        ref = '', )
                    ],
                also_known_as = [
                    ''
                    ],
                fullname_en = '',
                name = '',
                shortname_en = '',
                name_en = '',
                fullname = '',
                shortname = ''
            )
        else:
            return AuthorInPlayMetadata(
        )
        """

    def testAuthorInPlayMetadata(self):
        """Test AuthorInPlayMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
