# coding: utf-8

"""
    DraCor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.2
    Contact: fr.fischer@fu-berlin.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.play import Play

class TestPlay(unittest.TestCase):
    """Play unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Play:
        """Test Play
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Play`
        """
        model = Play()
        if include_optional:
            return Play(
                wikidata_id = '',
                segments = [
                    openapi_client.models.segment_item_in_play_metadata.SegmentItemInPlayMetadata(
                        type = '', 
                        speakers = [
                            ''
                            ], 
                        number = 56, 
                        title = '', )
                    ],
                corpus = '',
                year_premiered = '',
                all_in_index = 0.0,
                title_en = '',
                authors = [
                    openapi_client.models.author_in_play_metadata.AuthorInPlayMetadata(
                        refs = [
                            openapi_client.models.external_reference_resource_id.ExternalReferenceResourceId(
                                type = '', 
                                ref = '', )
                            ], 
                        also_known_as = [
                            ''
                            ], 
                        fullname_en = '', 
                        name = '', 
                        shortname_en = '', 
                        name_en = '', 
                        fullname = '', 
                        shortname = '', )
                    ],
                name = '',
                normalized_genre = '',
                subtitle_en = '',
                characters = [
                    openapi_client.models.character_in_play_metadata.CharacterInPlayMetadata(
                        wikidata_id = '', 
                        id = '', 
                        is_group = True, 
                        name = '', 
                        sex = 'MALE', )
                    ],
                source = openapi_client.models.source_in_play_metadata.SourceInPlayMetadata(
                    url = null, 
                    name = '', ),
                subtitle = '',
                libretto = True,
                all_in_segment = 56,
                year_written = '',
                id = '',
                date_premiered = '',
                year_printed = '',
                relations = [
                    openapi_client.models.relation_item_in_play_metadata.RelationItemInPlayMetadata(
                        directed = True, 
                        type = 'parent_of', 
                        source = '', 
                        target = '', )
                    ],
                title = '',
                year_normalized = 56,
                original_source = ''
            )
        else:
            return Play(
        )
        """

    def testPlay(self):
        """Test Play"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
